#!/bin/bash -e
set -e

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

echo 'Installing dependencies required by linter suite...'
npm --prefix $src_dir install --include=dev --omit=peer --force --no-audit

echo 'Running eslint for all javascript modules..'
echo ''

if eslint . \
    --max-warnings 0 \
    -c "${src_dir}/eslint.config.mjs" \
    ${src_dir}; then
    echo 'eslint succeeded'
    exit 0
else
    echo 'eslint found errors (see above)'
    exit 1
fi
