#!/bin/bash -e
set -e

src_dir="$(readlink -f "$(dirname "${0}")/..")"

eslint_cfg_filename="${1:-"eslint.config.mjs"}"
echo "Using linter cfg from ${eslint_cfg_filename}"

echo 'Installing dependencies required by linter suite...'
npm --prefix $src_dir install --include=dev --no-audit

echo 'Running eslint for all javascript modules..'
echo ''

npx --yes eslint . \
  --max-warnings 0 \
  -c "${src_dir}/${eslint_cfg_filename}" \
  "${src_dir}"

echo 'eslint succeeded'
